### ISSUE TITLE
Bug disclosure

### ISSUE THREAD

**Issue by gfeun** [stonehearth/startermod_items#1]
Hello ! 

I would like to inform the devs about a potentially important matter concerning this repo.
I sent an email to contact@radiant-entertainment.com 14 days ago but got no response.

Is there a way to contact a Radiant developer ?

Thanks !

**Comment by relyss** [comment]
Thanks for reaching out!
Found out your email and we're working on it.

**Comment by gfeun** [comment]
This seems fixed :) I close the issue.
